name: Build
on: 
  push:
  pull_request:
  workflow_dispatch: 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: getting the code
        uses: actions/checkout@v4
      - name: installing node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: installing dependencies
        run: npm ci
      - name: installing eslint
        run: npm install -D eslint eslint-config-next
      - name: linting the app
        run: npm run lint
      - name: building the site
        run: npm run build
        
  
